# Generated by Django 4.2.3 on 2023-08-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_alter_flatrate_name_alter_meterrate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteredbill',
            name='meter_number',
            field=models.IntegerField(default=0),
        ),
    ]
