# Generated by Django 4.2.3 on 2023-08-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_meteredbill_meter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteredbill',
            name='meter_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
