# Generated by Django 4.2.3 on 2023-08-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_alter_meteredbill_meter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='mult_factor',
            field=models.FloatField(default=1),
        ),
    ]
