# Generated by Django 4.2.3 on 2023-08-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_meter_mult_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteredbill',
            name='mult_factor',
            field=models.FloatField(default=1.0),
        ),
    ]
